version: "3.9"

services:
  ppoisdb:
    image: "postgres:latest"
    container_name: post_app
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER:  ${DB_USER}
    volumes:
      - 'db-data:/var/opt/mssql'

 
volumes:
  db-data:
    driver: local