version: "3.9"

services:
  api:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    environment:
      - DB_HOST=post_app_db
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    command: uvicorn social_app.main:social_app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - post_app_db
    restart: on-failure
  post_app_db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER:  ${DB_USER}
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports: 
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db-data:
    driver: local